### ISSUE TITLE
Experience for the number of training epochs

### ISSUE THREAD

**Issue by TillBeemelmanns** [dgriffiths3/mononet3d#2]
Hi @dgriffiths3 ,
thanks for sharing your code. Could you share your experience regarding the training duration. For how many years did you train the network to obtain reasonable evaluation results ? 
Best regards

**Comment by dgriffiths3** [comment]
Hi, I would usually train for approx. 6-12 hours on a Nvidia 1080ti GPU. The repository was never properly benchmarked with the evaluation data as it was a small part of a larger project, which I am no longer developing. I posted this here just so the code was not wasted.
